sudo: required

services:
- docker

language: javascript
dist: trusty

env:
- DOCKER_IMAGE=rsoairlines/fri-airlines-webapp:0.0.0

script:
- docker build -t "$DOCKER_IMAGE" .

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"