sudo: required

services:
- docker

language: javascript
dist: trusty

env:
- DOCKER_IMAGE=rsoairlines/fri-airlines-webapp:0.0.5

script:
- docker build -t "$DOCKER_IMAGE" .

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push "$DOCKER_IMAGE"