apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: rsoairlines/fri-airlines-webapp:0.0.4
        name: friairlines-webapp
        env:
        - name: environment
          value: production
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP